---
# The dataset to use, in this case, the OPUS Books dataset from Hugging Face that
# will be downloaded and cached in the local machine.
dataset:
  # Datasource name
  name: "opus_books"
  # The source language
  src_lang: "en"
  # The target language
  tgt_lang: "es"
  # Filter from the dataset the sentences exceding seq_len-2 tokens (long sentences)
  filter_long_sentences: true

# The model configuration
model:
  # Maximum sequence length
  seq_len: 350
  # Dimentionality of the embeddings
  d_model: 256
  # Number of heads in the multi-head attention
  num_heads: 4
  # Number of encoder layers
  num_encoder_layers: 2
  # Number of decoder layers
  num_decoder_layers: 2
  # The feedforward dimensionality for the last fully connected layer
  dim_feedforward: 1024
  # The dropout rate
  dropout: 0.1

# The training configuration
training:
  # The batch size
  batch_size: 12
  # The number of epochs to train
  num_epochs: 10
  # The learning rate
  lr: 0.0002
  # Folder name to save the model weights
  model_folder: "weights"
  # Basename for the model weights
  model_basename: "tmodel_"
  # The model to preload
  preload: "latest"
  # Tokenizer template: The {0} will be replaced by the language code
  tokenizer_file: "tokenizer_{0}.json"

tensorboard:
  # The folder to save the logs for Tensorboard
  log_dir: "runs/tmodel"
